services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: holymusic_app_rails_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    image: gedeon-app-rails:web
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: never
    command: jruby -S foreman start -f Procfile.docker
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      DATABASE_URL: jdbc:postgresql://db:5432/holymusic_app_rails_development?user=postgres&password=password

volumes:
  postgres-data:
